import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, EmptyState, MoneyText, Surface } from "@/components/finance-ui";
import { calculateAccountBalance } from "@/lib/finance-domain";
import { useFinance } from "@/lib/finance-store";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function AccountsScreen() {
  const { accounts, transactions, addAccount } = useFinance();
  const { colors } = useFinanceTheme();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [balance, setBalance] = useState("0,00");
  const save = () => { if (!name.trim()) return; addAccount({ name: name.trim(), type: "Conta corrente", institution: "", color: "#0B6B62", initialBalance: Number(balance.replace(/[.\s]/g, "").replace(",", ".")) || 0, includeInTotal: true }); setName(""); setBalance("0,00"); setOpen(false); };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppHeader title="Contas e carteiras" subtitle="Seu saldo é calculado pelas movimentações" back right={<Pressable onPress={() => setOpen(true)} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><MaterialIcons name="add" size={21} color="#FFFFFF" /></Pressable>} />
    {accounts.length ? <View style={styles.list}>{accounts.map((account) => <Surface key={account.id} style={styles.account}><View style={[styles.accountIcon, { backgroundColor: `${account.color}1A` }]}><MaterialIcons name={account.type === "Poupança" ? "savings" : "account-balance"} size={22} color={account.color} /></View><View style={styles.accountCopy}><Text style={[styles.accountName, { color: colors.text }]}>{account.name}</Text><Text style={[styles.accountMeta, { color: colors.muted }]}>{account.institution || account.type}</Text></View><MoneyText value={calculateAccountBalance(account, transactions)} style={styles.balance} /></Surface>)}</View> : <EmptyState icon="account-balance-wallet" title="Cadastre sua primeira conta" description="Contas ajudam a separar o dinheiro do dia a dia da sua reserva." action="Adicionar conta" onAction={() => setOpen(true)} />}
    <Text style={[styles.note, { color: colors.muted }]}>Os saldos são atualizados automaticamente a partir de receitas, despesas e transferências realizadas.</Text>
  </ScrollView><Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.sheet, { backgroundColor: colors.surface }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><Text style={[styles.sheetTitle, { color: colors.text }]}>Nova conta</Text><Text style={[styles.label, { color: colors.text }]}>Nome</Text><TextInput value={name} onChangeText={setName} placeholder="Ex.: Conta do dia a dia" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Text style={[styles.label, { color: colors.text, marginTop: 14 }]}>Saldo inicial</Text><TextInput value={balance} onChangeText={setBalance} placeholder="0,00" keyboardType="decimal-pad" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Pressable onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><Text style={styles.saveText}>Salvar conta</Text></Pressable><Pressable onPress={() => setOpen(false)} style={styles.cancel}><Text style={[styles.cancelText, { color: colors.muted }]}>Cancelar</Text></Pressable></View></View></Modal>
  </ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, add: { height: 40, width: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, list: { gap: 10 }, account: { flexDirection: "row", alignItems: "center", padding: 14, borderRadius: 20 }, accountIcon: { height: 45, width: 45, borderRadius: 15, alignItems: "center", justifyContent: "center", marginRight: 12 }, accountCopy: { flex: 1 }, accountName: { fontSize: 14, fontWeight: "800" }, accountMeta: { fontSize: 12, marginTop: 2 }, balance: { fontSize: 15 }, note: { fontSize: 12, lineHeight: 18, textAlign: "center", marginHorizontal: 20, marginTop: 20 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "#00000066" }, sheet: { padding: 22, paddingBottom: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { width: 38, height: 4, borderRadius: 3, alignSelf: "center", marginBottom: 19 }, sheetTitle: { fontSize: 20, fontWeight: "800", marginBottom: 18 }, label: { fontSize: 13, fontWeight: "800", marginBottom: 7 }, input: { height: 48, borderRadius: 13, borderWidth: 1, paddingHorizontal: 13, fontSize: 14, fontWeight: "600" }, save: { height: 51, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 21 }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, cancel: { alignItems: "center", marginTop: 13, padding: 7 }, cancelText: { fontSize: 13, fontWeight: "800" } });
