import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, EmptyState, MoneyText, ProgressBar, Surface } from "@/components/finance-ui";
import { currentMonth, getCardUsage } from "@/lib/finance-domain";
import { useFinance } from "@/lib/finance-store";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function CardsScreen() {
  const finance = useFinance(); const { colors } = useFinanceTheme(); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [limit, setLimit] = useState("1000,00");
  const save = () => { if (!name.trim()) return; finance.addCard({ name: name.trim(), brand: "Visa", lastDigits: "", limit: Number(limit.replace(/[.\s]/g, "").replace(",", ".")) || 1000, closingDay: 25, dueDay: 5, color: "#0B5D2A", accountId: finance.accounts[0]?.id }); setOpen(false); setName(""); };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppHeader title="Cartões" subtitle="Acompanhe limite e faturas" back right={<Pressable onPress={() => setOpen(true)} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><MaterialIcons name="add" size={21} color="#FFFFFF" /></Pressable>} />
    {finance.cards.length ? finance.cards.map((card) => { const used = getCardUsage(finance, card, currentMonth()); const available = Math.max(card.limit - used, 0); return <View key={card.id} style={[styles.card, { backgroundColor: card.color }]}><View style={styles.cardTop}><Text style={styles.cardBrand}>{card.brand.toUpperCase()}</Text><MaterialIcons name="contactless" size={23} color="#FFFFFF" /></View><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardDigits}>{card.lastDigits ? `•••• ${card.lastDigits}` : "Cartão de crédito"}</Text><View style={styles.cardBottom}><View><Text style={styles.cardLabel}>Disponível</Text><MoneyText value={available} style={styles.cardMoney} /></View><View style={{ alignItems: "flex-end" }}><Text style={styles.cardLabel}>Fecha dia {card.closingDay}</Text><Text style={styles.cardLimit}>Limite <MoneyText value={card.limit} style={styles.cardLimitMoney} /></Text></View></View><View style={styles.cardProgress}><ProgressBar value={card.limit ? (used / card.limit) * 100 : 0} color="#79D7C7" trackColor="#FFFFFF35" /></View></View>; }) : <EmptyState icon="credit-card" title="Nenhum cartão cadastrado" description="Registre seus cartões para enxergar compras e faturas antes do vencimento." action="Adicionar cartão" onAction={() => setOpen(true)} />}
    <Surface style={styles.tip}><MaterialIcons name="lightbulb-outline" size={20} color={colors.warning} /><Text style={[styles.tipText, { color: colors.muted }]}>Compras no cartão entram no relatório como despesas, sem duplicar quando a fatura for paga.</Text></Surface>
  </ScrollView><Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.sheet, { backgroundColor: colors.surface }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><Text style={[styles.sheetTitle, { color: colors.text }]}>Novo cartão</Text><Text style={[styles.label, { color: colors.text }]}>Nome do cartão</Text><TextInput value={name} onChangeText={setName} placeholder="Ex.: Meu cartão principal" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Text style={[styles.label, { color: colors.text, marginTop: 14 }]}>Limite total</Text><TextInput value={limit} onChangeText={setLimit} keyboardType="decimal-pad" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Pressable onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><Text style={styles.saveText}>Salvar cartão</Text></Pressable><Pressable onPress={() => setOpen(false)} style={styles.cancel}><Text style={[styles.cancelText, { color: colors.muted }]}>Cancelar</Text></Pressable></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, add: { height: 40, width: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, card: { borderRadius: 23, padding: 19, marginBottom: 12, minHeight: 210, shadowColor: "#063D1D", shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 2 }, cardTop: { flexDirection: "row", justifyContent: "space-between" }, cardBrand: { color: "#FFFFFFAA", fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, cardName: { color: "#FFFFFF", fontSize: 20, fontWeight: "800", marginTop: 30 }, cardDigits: { color: "#FFFFFFC8", fontSize: 13, marginTop: 6, letterSpacing: 1.2 }, cardBottom: { flexDirection: "row", justifyContent: "space-between", marginTop: 24 }, cardLabel: { color: "#FFFFFFA8", fontSize: 11, fontWeight: "600" }, cardMoney: { color: "#FFFFFF", fontSize: 16, marginTop: 3 }, cardLimit: { color: "#FFFFFFD8", fontSize: 11, marginTop: 4 }, cardLimitMoney: { color: "#FFFFFF", fontSize: 11 }, cardProgress: { marginTop: 12 }, tip: { borderRadius: 17, flexDirection: "row", gap: 10, alignItems: "flex-start", padding: 14, marginTop: 8 }, tipText: { flex: 1, fontSize: 12, lineHeight: 17 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "#00000066" }, sheet: { padding: 22, paddingBottom: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { width: 38, height: 4, borderRadius: 3, alignSelf: "center", marginBottom: 19 }, sheetTitle: { fontSize: 20, fontWeight: "800", marginBottom: 18 }, label: { fontSize: 13, fontWeight: "800", marginBottom: 7 }, input: { height: 48, borderRadius: 13, borderWidth: 1, paddingHorizontal: 13, fontSize: 14, fontWeight: "600" }, save: { height: 51, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 21 }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, cancel: { alignItems: "center", marginTop: 13, padding: 7 }, cancelText: { fontSize: 13, fontWeight: "800" } });
