import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, EmptyState, MoneyText, Surface } from "@/components/finance-ui";
import { currentMonth, getCategorySpending } from "@/lib/finance-domain";
import { useFinance } from "@/lib/finance-store";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function CategoriesScreen() {
  const finance = useFinance(); const { colors } = useFinanceTheme(); const [kind, setKind] = useState<"expense" | "income">("expense"); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const month = currentMonth();
  const visible = useMemo(() => finance.categories.filter((category) => category.kind === kind && !category.archived), [finance.categories, kind]);
  const save = () => { if (!name.trim()) return; finance.addCategory({ name: name.trim(), kind, color: kind === "income" ? "#00843D" : "#62A744", icon: kind === "income" ? "payments" : "category" }); setName(""); setOpen(false); };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppHeader title="Categorias" subtitle="Dê contexto aos seus lançamentos" back right={<Pressable onPress={() => setOpen(true)} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><MaterialIcons name="add" size={21} color="#FFFFFF" /></Pressable>} />
    <View style={styles.segment}><Segment active={kind === "expense"} label="Despesas" onPress={() => setKind("expense")} /><Segment active={kind === "income"} label="Receitas" onPress={() => setKind("income")} /></View>
    {visible.length ? <View style={styles.list}>{visible.map((category) => { const budget = finance.budgets.find((value) => value.categoryId === category.id && value.month === month); const used = getCategorySpending(finance, month, category.id); return <Surface key={category.id} style={styles.category}><View style={[styles.categoryIcon, { backgroundColor: `${category.color}18` }]}><MaterialIcons name={category.icon as keyof typeof MaterialIcons.glyphMap} size={20} color={category.color} /></View><View style={styles.categoryCopy}><Text style={[styles.categoryName, { color: colors.text }]}>{category.name}</Text><Text style={[styles.categoryDetail, { color: colors.muted }]}>{kind === "expense" ? budget ? "Orçamento definido" : "Sem orçamento" : "Categoria de receita"}</Text></View>{kind === "expense" ? <View style={styles.categoryValue}><MoneyText value={used} style={styles.usedMoney} /><Text style={[styles.categoryLabel, { color: colors.muted }]}>{budget ? "usados" : "no mês"}</Text></View> : null}</Surface>; })}</View> : <EmptyState icon="category" title="Sem categorias" description="Crie uma categoria para encontrar seus lançamentos com facilidade." action="Adicionar categoria" onAction={() => setOpen(true)} />}
    {kind === "expense" ? <Surface style={styles.budgetHint}><MaterialIcons name="donut-large" size={20} color={colors.primary} /><View style={styles.hintCopy}><Text style={[styles.hintTitle, { color: colors.text }]}>Orçamentos</Text><Text style={[styles.hintText, { color: colors.muted }]}>O planejamento mostra os limites já definidos para cada categoria.</Text></View></Surface> : null}
  </ScrollView><Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.sheet, { backgroundColor: colors.surface }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><Text style={[styles.sheetTitle, { color: colors.text }]}>Nova categoria</Text><Text style={[styles.label, { color: colors.text }]}>Nome</Text><TextInput value={name} onChangeText={setName} placeholder={kind === "expense" ? "Ex.: Assinaturas" : "Ex.: Reembolso"} placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Pressable onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: colors.primary, opacity: pressed ? 0.8 : 1 }]}><Text style={styles.saveText}>Salvar categoria</Text></Pressable><Pressable onPress={() => setOpen(false)} style={styles.cancel}><Text style={[styles.cancelText, { color: colors.muted }]}>Cancelar</Text></Pressable></View></View></Modal></ScreenContainer>;
}
function Segment({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { const { colors } = useFinanceTheme(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.segmentButton, { backgroundColor: active ? colors.surface : "transparent", opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.segmentText, { color: active ? colors.primary : colors.muted }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, add: { height: 40, width: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, segment: { flexDirection: "row", padding: 4, borderRadius: 15, backgroundColor: "#00000009", marginTop: 3, marginBottom: 16 }, segmentButton: { flex: 1, height: 39, borderRadius: 12, alignItems: "center", justifyContent: "center" }, segmentText: { fontSize: 13, fontWeight: "800" }, list: { gap: 9 }, category: { flexDirection: "row", alignItems: "center", padding: 13, borderRadius: 18 }, categoryIcon: { height: 40, width: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", marginRight: 10 }, categoryCopy: { flex: 1 }, categoryName: { fontSize: 14, fontWeight: "800" }, categoryDetail: { fontSize: 11, marginTop: 2 }, categoryValue: { alignItems: "flex-end" }, usedMoney: { fontSize: 13 }, categoryLabel: { fontSize: 10, marginTop: 1 }, budgetHint: { borderRadius: 18, flexDirection: "row", alignItems: "center", padding: 14, marginTop: 20 }, hintCopy: { flex: 1, marginLeft: 10 }, hintTitle: { fontSize: 13, fontWeight: "800" }, hintText: { fontSize: 11, lineHeight: 16, marginTop: 1 }, overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "#00000066" }, sheet: { padding: 22, paddingBottom: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { width: 38, height: 4, borderRadius: 3, alignSelf: "center", marginBottom: 19 }, sheetTitle: { fontSize: 20, fontWeight: "800", marginBottom: 18 }, label: { fontSize: 13, fontWeight: "800", marginBottom: 7 }, input: { height: 48, borderRadius: 13, borderWidth: 1, paddingHorizontal: 13, fontSize: 14, fontWeight: "600" }, save: { height: 51, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 21 }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, cancel: { alignItems: "center", marginTop: 13, padding: 7 }, cancelText: { fontSize: 13, fontWeight: "800" } });
