import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/lib/auth-provider";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function DeleteAccountScreen() {
  const { colors } = useFinanceTheme(); const { requestAccountDeletion } = useAuth(); const [confirmation, setConfirmation] = useState(''); const [loading, setLoading] = useState(false); const [feedback, setFeedback] = useState('');
  const submit = async () => { if (confirmation !== 'EXCLUIR') { setFeedback('Digite EXCLUIR para confirmar esta solicitação.'); return; } setLoading(true); setFeedback(''); try { await requestAccountDeletion(); setFeedback('Solicitação registrada. Vamos tratar a exclusão da conta e dos dados associados.'); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Não foi possível registrar sua solicitação.'); } finally { setLoading(false); } };
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Pressable accessibilityRole="button" accessibilityLabel="Voltar" onPress={() => router.back()} style={({ pressed }) => [styles.back, { backgroundColor: colors.elevated, opacity: pressed ? .65 : 1 }]}><MaterialIcons name="arrow-back" size={20} color={colors.text} /></Pressable><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Solicitar exclusão da conta</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Essa ação inicia a remoção da sua conta e dos dados financeiros associados. Ela não pode ser desfeita depois da conclusão.</Text><View style={[styles.warning, { backgroundColor: `${colors.negative}12` }]}><MaterialIcons name="warning-amber" size={21} color={colors.negative} /><Text style={[styles.warningText, { color: colors.text }]}>Antes de confirmar, exporte o que quiser guardar. Esta é uma solicitação registrada, não uma exclusão instantânea no aparelho.</Text></View><Text style={[styles.label, { color: colors.text }]}>Digite EXCLUIR para confirmar</Text><TextInput accessibilityLabel="Digite EXCLUIR para confirmar" accessibilityHint={feedback && confirmation !== 'EXCLUIR' ? feedback : undefined} value={confirmation} onChangeText={(value) => { setConfirmation(value.toUpperCase()); setFeedback(''); }} autoCapitalize="characters" placeholder="EXCLUIR" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: feedback && confirmation !== 'EXCLUIR' ? colors.negative : colors.border }]} /><Pressable accessibilityRole="button" disabled={loading} onPress={submit} style={({ pressed }) => [styles.delete, { backgroundColor: colors.negative, opacity: pressed || loading ? .65 : 1 }]}>{loading ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.deleteText}>Registrar solicitação de exclusão</Text>}</Pressable>{feedback ? <Text accessibilityLiveRegion="polite" style={[styles.feedback, { color: feedback.startsWith('Solicitação') ? colors.positive : colors.negative }]}>{feedback}</Text> : null}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 35, maxWidth: 640, width: '100%', alignSelf: 'center' }, back: { width: 42, height: 42, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginBottom: 28 }, title: { fontSize: 30, fontWeight: '900', letterSpacing: -.8, lineHeight: 37 }, subtitle: { fontSize: 14, lineHeight: 21, marginTop: 10 }, warning: { borderRadius: 18, padding: 15, flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 27 }, warningText: { flex: 1, fontSize: 13, lineHeight: 19, fontWeight: '700' }, label: { fontSize: 13, fontWeight: '900', marginTop: 25, marginBottom: 8 }, input: { height: 51, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, fontSize: 15, fontWeight: '800', letterSpacing: .5 }, delete: { height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 14 }, deleteText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' }, feedback: { fontSize: 13, lineHeight: 19, fontWeight: '700', marginTop: 14 } });
