import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, MoneyText, ProgressBar, SectionTitle, Surface } from "@/components/finance-ui";
import { currentMonth, formatMonth, getCategorySpending, getMonthlySummary } from "@/lib/finance-domain";
import { useFinance } from "@/lib/finance-store";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function ReportsScreen() {
  const finance = useFinance(); const { colors } = useFinanceTheme(); const month = currentMonth(); const summary = getMonthlySummary(finance, month); const expenses = finance.categories.filter((category) => category.kind === "expense").map((category) => ({ category, value: getCategorySpending(finance, month, category.id) })).filter((item) => item.value > 0).sort((a, b) => b.value - a.value);
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppHeader title="Relatórios" subtitle={formatMonth(month)} back /><Surface style={styles.summary}><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>Resultado do mês</Text><MoneyText value={summary.result} style={styles.result} positive={summary.result >= 0} negative={summary.result < 0} /></View><View style={[styles.summaryIcon, { backgroundColor: summary.result >= 0 ? `${colors.positive}18` : `${colors.negative}18` }]}><MaterialIcons name={summary.result >= 0 ? "trending-up" : "trending-down"} size={24} color={summary.result >= 0 ? colors.positive : colors.negative} /></View></Surface><SectionTitle title="Entradas e saídas" /><Surface style={styles.chart}><View style={styles.chartRow}><View style={styles.dotIncome} /><Text style={[styles.chartName, { color: colors.text }]}>Receitas</Text><MoneyText value={summary.income} style={styles.chartMoney} positive /></View><ProgressBar value={100} color={colors.positive} /><View style={[styles.chartRow, { marginTop: 18 }]}><View style={styles.dotExpense} /><Text style={[styles.chartName, { color: colors.text }]}>Despesas</Text><MoneyText value={summary.expenses} style={styles.chartMoney} negative /></View><ProgressBar value={summary.income ? (summary.expenses / summary.income) * 100 : 0} color={colors.negative} /></Surface><SectionTitle title="Despesas por categoria" /><Surface style={styles.categoryChart}>{expenses.length ? expenses.map(({ category, value }) => <View key={category.id} style={styles.reportCategory}><View style={styles.reportCategoryTop}><View style={styles.reportNameWrap}><View style={[styles.reportDot, { backgroundColor: category.color }]} /><Text style={[styles.reportName, { color: colors.text }]}>{category.name}</Text></View><MoneyText value={value} style={styles.reportMoney} /></View><ProgressBar value={summary.expenses ? (value / summary.expenses) * 100 : 0} color={category.color} /></View>) : <Text style={[styles.empty, { color: colors.muted }]}>Registre despesas para visualizar esta análise.</Text>}</Surface><SectionTitle title="O que este painel mostra" /><Surface style={styles.info}><MaterialIcons name="info-outline" size={20} color={colors.primary} /><Text style={[styles.infoText, { color: colors.muted }]}>Transferências não entram como receita ou despesa. Valores pendentes influenciam a previsão, sem alterar o saldo realizado.</Text></Surface></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, summary: { borderRadius: 21, flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 17 }, summaryLabel: { fontSize: 12, fontWeight: "700" }, result: { fontSize: 26, marginTop: 4 }, summaryIcon: { height: 48, width: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, chart: { borderRadius: 20, padding: 16 }, chartRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 }, dotIncome: { height: 9, width: 9, borderRadius: 5, backgroundColor: "#00843D", marginRight: 8 }, dotExpense: { height: 9, width: 9, borderRadius: 5, backgroundColor: "#C74646", marginRight: 8 }, chartName: { flex: 1, fontSize: 13, fontWeight: "800" }, chartMoney: { fontSize: 13 }, categoryChart: { borderRadius: 20, padding: 16 }, reportCategory: { marginBottom: 16 }, reportCategoryTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 7 }, reportNameWrap: { flexDirection: "row", alignItems: "center" }, reportDot: { height: 9, width: 9, borderRadius: 5, marginRight: 8 }, reportName: { fontSize: 13, fontWeight: "800" }, reportMoney: { fontSize: 13 }, empty: { textAlign: "center", fontSize: 13, paddingVertical: 8 }, info: { borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "flex-start", gap: 10 }, infoText: { flex: 1, fontSize: 12, lineHeight: 18 } });
