import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, Surface } from "@/components/finance-ui";
import { useFinance } from "@/lib/finance-store";
import { type ThemePreference, useFinanceTheme } from "@/lib/finance-theme";

export default function SettingsScreen() {
  const { privacyMode, setPrivacyMode, demoMode, completeWelcome } = useFinance(); const { colors, preference, setPreference } = useFinanceTheme();
  const beginOwnData = () => Alert.alert("Começar com dados próprios?", "Os dados de demonstração serão substituídos por uma base vazia neste dispositivo.", [{ text: "Cancelar", style: "cancel" }, { text: "Continuar", style: "destructive", onPress: () => completeWelcome("fresh") }]);
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><AppHeader title="Configurações" subtitle="Preferências e privacidade" back /><Text style={[styles.section, { color: colors.muted }]}>APARÊNCIA</Text><Surface style={styles.block}><Text style={[styles.blockTitle, { color: colors.text }]}>Tema</Text><View style={styles.themeRow}>{(["light", "system", "dark"] as ThemePreference[]).map((item) => <Pressable key={item} onPress={() => setPreference(item)} style={({ pressed }) => [styles.themeOption, { backgroundColor: preference === item ? colors.accent : colors.elevated, borderColor: preference === item ? colors.primary : "transparent", opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name={item === "light" ? "light-mode" : item === "dark" ? "dark-mode" : "brightness-auto"} size={17} color={preference === item ? colors.primary : colors.muted} /><Text style={[styles.themeText, { color: preference === item ? colors.primary : colors.text }]}>{item === "light" ? "Claro" : item === "dark" ? "Escuro" : "Auto"}</Text></Pressable>)}</View></Surface><Text style={[styles.section, { color: colors.muted }]}>PRIVACIDADE</Text><Surface style={styles.settingRow}><View style={[styles.settingIcon, { backgroundColor: colors.accent }]}><MaterialIcons name="visibility-off" size={20} color={colors.primary} /></View><View style={styles.settingCopy}><Text style={[styles.settingTitle, { color: colors.text }]}>Ocultar valores</Text><Text style={[styles.settingText, { color: colors.muted }]}>Substitui os valores por asteriscos.</Text></View><Switch value={privacyMode} onValueChange={setPrivacyMode} trackColor={{ false: colors.border, true: colors.primary }} thumbColor="#FFFFFF" /></Surface><Text style={[styles.section, { color: colors.muted }]}>DADOS</Text>{demoMode ? <Pressable onPress={beginOwnData} style={({ pressed }) => [styles.dataAction, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><View style={[styles.settingIcon, { backgroundColor: "#FFF2D8" }]}><MaterialIcons name="edit-note" size={20} color={colors.warning} /></View><View style={styles.settingCopy}><Text style={[styles.settingTitle, { color: colors.text }]}>Começar com dados próprios</Text><Text style={[styles.settingText, { color: colors.muted }]}>Sai do modo de demonstração neste dispositivo.</Text></View><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></Pressable> : null}<Surface style={styles.notice}><MaterialIcons name="lock-outline" size={20} color={colors.primary} /><Text style={[styles.noticeText, { color: colors.muted }]}>Nesta versão, os dados ficam guardados localmente no dispositivo. A sincronização segura com conta de usuário está preparada como próxima etapa de produção.</Text></Surface></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 28 }, section: { fontSize: 10, letterSpacing: 0.9, fontWeight: "800", marginTop: 23, marginBottom: 8, marginLeft: 3 }, block: { borderRadius: 19, padding: 14 }, blockTitle: { fontSize: 14, fontWeight: "800", marginBottom: 12 }, themeRow: { flexDirection: "row", gap: 7 }, themeOption: { flex: 1, height: 42, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 5 }, themeText: { fontSize: 11, fontWeight: "800" }, settingRow: { borderRadius: 19, padding: 14, flexDirection: "row", alignItems: "center" }, settingIcon: { height: 40, width: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", marginRight: 11 }, settingCopy: { flex: 1 }, settingTitle: { fontSize: 14, fontWeight: "800" }, settingText: { fontSize: 11, lineHeight: 16, marginTop: 2 }, dataAction: { borderRadius: 19, borderWidth: 1, padding: 14, flexDirection: "row", alignItems: "center" }, notice: { borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "flex-start", gap: 10, marginTop: 12 }, noticeText: { flex: 1, fontSize: 12, lineHeight: 18 } });
