import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { AppHeader, EmptyState, MoneyText, ProgressBar, SectionTitle, Surface } from "@/components/finance-ui";
import { currentMonth, formatDate, getCategorySpending } from "@/lib/finance-domain";
import { useFinance } from "@/lib/finance-store";
import { useFinanceTheme } from "@/lib/finance-theme";

export default function PlanningScreen() {
  const finance = useFinance();
  const { colors } = useFinanceTheme();
  const month = currentMonth();
  return <ScreenContainer><FlatList data={finance.budgets} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}
    ListHeaderComponent={<View><AppHeader title="Planejamento" subtitle="Orçamentos e metas em um só lugar" /><SectionTitle title="Sua meta principal" action="Ver metas" onAction={() => router.push("/more")} />{finance.goals[0] ? <GoalCard goal={finance.goals[0]} colors={colors} /> : <EmptyState icon="flag" title="Crie sua primeira meta" description="Metas tornam o seu plano mais concreto." />}{<SectionTitle title="Orçamentos do mês" action="Ajustar" onAction={() => router.push("/categories" as never)} />}</View>}
    renderItem={({ item }) => { const category = finance.categories.find((value) => value.id === item.categoryId); const used = getCategorySpending(finance, month, item.categoryId); const ratio = item.amount ? (used / item.amount) * 100 : 0; const color = ratio > 90 ? colors.negative : ratio > 70 ? colors.warning : colors.positive; return <Surface style={styles.budgetCard}><View style={styles.budgetTop}><View style={[styles.budgetIcon, { backgroundColor: `${category?.color ?? colors.primary}1A` }]}><MaterialIcons name={(category?.icon as keyof typeof MaterialIcons.glyphMap) ?? "category"} size={19} color={category?.color ?? colors.primary} /></View><View style={styles.budgetTitleWrap}><Text style={[styles.budgetTitle, { color: colors.text }]}>{category?.name ?? "Categoria"}</Text><Text style={[styles.budgetCaption, { color: colors.muted }]}>{Math.round(ratio)}% utilizado</Text></View><MoneyText value={Math.max(item.amount - used, 0)} style={styles.remaining} /></View><ProgressBar value={ratio} color={color} /><View style={styles.budgetDetails}><Text style={[styles.budgetDetail, { color: colors.muted }]}><Text style={{ color: colors.text, fontWeight: "800" }}><MoneyText value={used} style={styles.inlineMoney} /></Text> usados</Text><Text style={[styles.budgetDetail, { color: colors.muted }]}>de <MoneyText value={item.amount} style={styles.inlineMoney} /></Text></View></Surface>; }}
    ListEmptyComponent={<EmptyState icon="donut-large" title="Sem orçamentos neste mês" description="Defina um limite para acompanhar seus gastos com mais clareza." action="Gerenciar categorias" onAction={() => router.push("/categories" as never)} />}
    ListFooterComponent={<View style={{ height: 24 }} />}
  /></ScreenContainer>;
}

function GoalCard({ goal, colors }: { goal: ReturnType<typeof useFinance>["goals"][number]; colors: ReturnType<typeof useFinanceTheme>["colors"] }) { const progress = (goal.saved / goal.target) * 100; return <Surface style={styles.goalCard}><View style={styles.goalTop}><View><Text style={[styles.goalKicker, { color: colors.muted }]}>META FINANCEIRA</Text><Text style={[styles.goalName, { color: colors.text }]}>{goal.name}</Text></View><View style={[styles.goalIcon, { backgroundColor: colors.accent }]}><MaterialIcons name="flag" size={20} color={colors.primary} /></View></View><MoneyText value={goal.saved} style={styles.goalValue} /><Text style={[styles.goalTarget, { color: colors.muted }]}>de <MoneyText value={goal.target} style={styles.inlineMoney} /> até {formatDate(goal.targetDate)}</Text><ProgressBar value={progress} color={goal.color} /><Text style={[styles.goalProgress, { color: colors.primary }]}>{Math.round(progress)}% concluído</Text></Surface>; }
const styles = StyleSheet.create({
  content: { paddingHorizontal: 20, paddingBottom: 20 }, goalCard: { borderRadius: 22, padding: 17 }, goalTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, goalKicker: { fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, goalName: { fontSize: 17, fontWeight: "800", marginTop: 4 }, goalIcon: { height: 40, width: 40, borderRadius: 14, alignItems: "center", justifyContent: "center" }, goalValue: { fontSize: 25, marginTop: 18 }, goalTarget: { fontSize: 12, marginTop: 3, marginBottom: 14 }, goalProgress: { fontSize: 12, fontWeight: "800", marginTop: 8 }, budgetCard: { marginBottom: 10, borderRadius: 19, padding: 14 }, budgetTop: { flexDirection: "row", alignItems: "center", marginBottom: 12 }, budgetIcon: { height: 39, width: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", marginRight: 10 }, budgetTitleWrap: { flex: 1 }, budgetTitle: { fontSize: 14, fontWeight: "800" }, budgetCaption: { fontSize: 11, marginTop: 2 }, remaining: { fontSize: 14 }, budgetDetails: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 }, budgetDetail: { fontSize: 11 }, inlineMoney: { fontSize: 12, fontWeight: "800" },
});
